// Generated by scripts/fetch-demo-fonts.mjs — do not edit by hand.
// Self-hosted, OFL-licensed Google Fonts for the template demos (see src/app/fonts/demos/LICENSE.md).
import localFont from "next/font/local";

export const plex = localFont({
  variable: "--font-plex",
  display: "swap",
  preload: false,
  src: [
    { path: "../app/fonts/demos/plex-400.woff", weight: "400", style: "normal" },
    { path: "../app/fonts/demos/plex-500.woff", weight: "500", style: "normal" },
    { path: "../app/fonts/demos/plex-600.woff", weight: "600", style: "normal" },
    { path: "../app/fonts/demos/plex-700.woff", weight: "700", style: "normal" },
  ],
});

export const playfair = localFont({
  variable: "--font-playfair",
  display: "swap",
  preload: false,
  src: [
    { path: "../app/fonts/demos/playfair-400.woff", weight: "400", style: "normal" },
    { path: "../app/fonts/demos/playfair-700.woff", weight: "700", style: "normal" },
  ],
});

export const amiri = localFont({
  variable: "--font-amiri",
  display: "swap",
  preload: false,
  src: [
    { path: "../app/fonts/demos/amiri-400.woff", weight: "400", style: "normal" },
    { path: "../app/fonts/demos/amiri-700.woff", weight: "700", style: "normal" },
  ],
});

export const cormorant = localFont({
  variable: "--font-cormorant",
  display: "swap",
  preload: false,
  src: [
    { path: "../app/fonts/demos/cormorant-400-italic.woff", weight: "400", style: "italic" },
    { path: "../app/fonts/demos/cormorant-400.woff", weight: "400", style: "normal" },
    { path: "../app/fonts/demos/cormorant-500.woff", weight: "500", style: "normal" },
    { path: "../app/fonts/demos/cormorant-600.woff", weight: "600", style: "normal" },
  ],
});

export const reem = localFont({
  variable: "--font-reem",
  display: "swap",
  preload: false,
  src: [
    { path: "../app/fonts/demos/reem-400.woff", weight: "400", style: "normal" },
    { path: "../app/fonts/demos/reem-600.woff", weight: "600", style: "normal" },
  ],
});

export const fraunces = localFont({
  variable: "--font-fraunces",
  display: "swap",
  preload: false,
  src: [
    { path: "../app/fonts/demos/fraunces-400.woff", weight: "400", style: "normal" },
    { path: "../app/fonts/demos/fraunces-700.woff", weight: "700", style: "normal" },
  ],
});

export const lalezar = localFont({
  variable: "--font-lalezar",
  display: "swap",
  preload: false,
  src: [
    { path: "../app/fonts/demos/lalezar-400.woff", weight: "400", style: "normal" },
  ],
});

export const rubik = localFont({
  variable: "--font-rubik",
  display: "swap",
  preload: false,
  src: [
    { path: "../app/fonts/demos/rubik-400.woff", weight: "400", style: "normal" },
    { path: "../app/fonts/demos/rubik-500.woff", weight: "500", style: "normal" },
    { path: "../app/fonts/demos/rubik-700.woff", weight: "700", style: "normal" },
  ],
});

export const cairo = localFont({
  variable: "--font-cairo",
  display: "swap",
  preload: false,
  src: [
    { path: "../app/fonts/demos/cairo-400.woff", weight: "400", style: "normal" },
    { path: "../app/fonts/demos/cairo-600.woff", weight: "600", style: "normal" },
    { path: "../app/fonts/demos/cairo-700.woff", weight: "700", style: "normal" },
    { path: "../app/fonts/demos/cairo-800.woff", weight: "800", style: "normal" },
  ],
});

export const manrope = localFont({
  variable: "--font-manrope",
  display: "swap",
  preload: false,
  src: [
    { path: "../app/fonts/demos/manrope-400.woff", weight: "400", style: "normal" },
    { path: "../app/fonts/demos/manrope-600.woff", weight: "600", style: "normal" },
    { path: "../app/fonts/demos/manrope-700.woff", weight: "700", style: "normal" },
    { path: "../app/fonts/demos/manrope-800.woff", weight: "800", style: "normal" },
  ],
});

export const inter = localFont({
  variable: "--font-inter",
  display: "swap",
  preload: false,
  src: [
    { path: "../app/fonts/demos/inter-400.woff", weight: "400", style: "normal" },
    { path: "../app/fonts/demos/inter-500.woff", weight: "500", style: "normal" },
    { path: "../app/fonts/demos/inter-600.woff", weight: "600", style: "normal" },
    { path: "../app/fonts/demos/inter-700.woff", weight: "700", style: "normal" },
    { path: "../app/fonts/demos/inter-800.woff", weight: "800", style: "normal" },
  ],
});

export const tajawal = localFont({
  variable: "--font-tajawal",
  display: "swap",
  preload: false,
  src: [
    { path: "../app/fonts/demos/tajawal-400.woff", weight: "400", style: "normal" },
    { path: "../app/fonts/demos/tajawal-500.woff", weight: "500", style: "normal" },
    { path: "../app/fonts/demos/tajawal-700.woff", weight: "700", style: "normal" },
    { path: "../app/fonts/demos/tajawal-800.woff", weight: "800", style: "normal" },
  ],
});

export const notoArabic = localFont({
  variable: "--font-noto-arabic",
  display: "swap",
  preload: false,
  src: [
    { path: "../app/fonts/demos/notoArabic-400.woff", weight: "400", style: "normal" },
    { path: "../app/fonts/demos/notoArabic-500.woff", weight: "500", style: "normal" },
    { path: "../app/fonts/demos/notoArabic-700.woff", weight: "700", style: "normal" },
  ],
});
