import type { DemoLang } from "@/demos/config";

const en = {
  brand: "Nawa Clinic",
  brandSub: "Care, with consideration",
  demoLabel: "A fictional clinic · Website demo",
  nav: {
    care: "Our care",
    team: "The team",
    journey: "Your visit",
    faq: "Questions",
  },
  cta: "Try a booking",
  hero: {
    eyebrow: "A little more time. A little more understanding.",
    title: "Good care starts",
    accent: "with listening.",
    text: "A place for your questions, your everyday health, and a conversation about what comes next. Get to know a more considered approach to care.",
    primary: "Plan a first visit",
    secondary: "Explore our care",
    imageAlt:
      "An illustrative clinic reception with warm wood, soft daylight and quiet seating",
    imageLabel: "A calmer beginning",
    imageText: "Room to pause. Space to talk.",
    detail: "For everyday health, and the questions in between.",
  },
  principles: [
    { title: "Time to be heard", text: "Start with what matters to you." },
    {
      title: "Care, explained",
      text: "Understand your options and next steps.",
    },
    {
      title: "A shared plan",
      text: "Make room for your needs and preferences.",
    },
  ],
  care: {
    eyebrow: "Ways we can help",
    title: "Everyday care.\nIndividual attention.",
    text: "From a first conversation to a follow-up, find the kind of appointment that fits your question.",
    link: "Discuss a visit",
    items: [
      {
        id: "general",
        icon: "stethoscope",
        title: "General medicine",
        tag: "A place to start",
        text: "Bring a new concern, talk about your general health, or revisit an ongoing care plan with a clinician.",
        detail: "Consultations · Follow-up visits",
      },
      {
        id: "dental",
        icon: "smile",
        title: "Dental care",
        tag: "Everyday confidence",
        text: "A conversation about your teeth and gums, routine dental checks, and a clear explanation of treatment options.",
        detail: "Dental checks · Care planning",
      },
      {
        id: "skin",
        icon: "sun",
        title: "Skin health",
        tag: "Questions welcome",
        text: "Discuss a skin concern and what you hope to understand. Explore an approach based on an individual assessment.",
        detail: "Skin consultations · Reviews",
      },
      {
        id: "movement",
        icon: "activity",
        title: "Movement & recovery",
        tag: "Life in motion",
        text: "Talk through movement difficulties, everyday activities, and the goals you would like to work towards.",
        detail: "Physiotherapy · Follow-up care",
      },
    ],
  },
  approach: {
    eyebrow: "Our approach",
    title: "You bring the questions.\nWe make room for them.",
    text: "A useful appointment begins with a conversation. The aim is to understand your priorities, explain the available options, and agree on a sensible next step together.",
    note: "Nothing has to be too small to ask about.",
    labels: ["Listen", "Understand", "Plan together"],
  },
  team: {
    eyebrow: "People behind the care",
    title: "A thoughtful team.\nA human conversation.",
    text: "Different areas of care, one shared starting point: listening to the person in front of us.",
    demoNote: "Illustrative team profiles for this fictional clinic.",
    label: "Care focus",
    members: [
      {
        id: "lina",
        initials: "LN",
        name: "Dr. Lina Nader",
        role: "General medicine",
        focus: "First visits & ongoing care",
        bio: "A starting point for everyday health questions and conversations about follow-up care.",
      },
      {
        id: "adam",
        initials: "AS",
        name: "Dr. Adam Salem",
        role: "Dental care",
        focus: "Dental checks & care planning",
        bio: "An approachable conversation about oral health, available options, and the next visit.",
      },
      {
        id: "maya",
        initials: "MO",
        name: "Dr. Maya Omar",
        role: "Skin health",
        focus: "Consultations & reviews",
        bio: "Time to discuss a skin concern, understand the assessment, and ask your questions.",
      },
    ],
  },
  journey: {
    eyebrow: "Before your first visit",
    title: "A clear path,\none step at a time.",
    text: "Knowing what to expect can make a new place feel more familiar. Here is how a visit could unfold.",
    link: "Explore the booking demo",
    steps: [
      {
        title: "Choose a starting point",
        text: "Select an area of care and a preferred part of the day. In a live clinic, the reception team would confirm the details.",
      },
      {
        title: "Make space for a conversation",
        text: "Share the questions you want to discuss. An appointment is also a chance to understand the options available to you.",
      },
      {
        title: "Understand what comes next",
        text: "Discuss the plan, any follow-up, and how to raise further questions. Take time to ask for an explanation when you need one.",
      },
    ],
  },
  booking: {
    eyebrow: "Your next step",
    title: "Let’s make\nroom for you.",
    text: "Explore a simple appointment request. Choose the care you are interested in and a time preference to see how the experience works.",
    privacy:
      "Use sample details only. Please do not enter medical information.",
    formTitle: "Try an appointment request",
    demoLabel: "Demo booking",
    fields: {
      name: "Your name",
      namePlaceholder: "Sample name",
      email: "Email address",
      emailPlaceholder: "name@example.com",
      care: "Area of care",
      carePlaceholder: "Choose an area",
      time: "Preferred time",
      timePlaceholder: "Choose a preference",
      timeOptions: ["Morning", "Afternoon", "No preference"],
    },
    submit: "Preview my request",
    note: "Demo only. Nothing is sent or booked.",
    success: {
      title: "You’ve tried the booking demo",
      text: "No appointment was created and no information was sent. This is the confirmation experience a visitor would see in the template.",
      again: "Try another request",
    },
  },
  faq: {
    eyebrow: "A few things to know",
    title: "Questions,\nanswered simply.",
    text: "A little clarity before you take the next step.",
    items: [
      {
        q: "Is Nawa a real clinic?",
        a: "Nawa is a fictional brand created to demonstrate this website template. The care descriptions, team profiles, location, and opening hours are illustrative. No medical services are offered through this page.",
      },
      {
        q: "Will the booking form make an appointment?",
        a: "No. It lets you try the form and see a confirmation screen. Nothing is sent, saved as a booking, or shared with a clinic. Please use sample details only.",
      },
      {
        q: "What if I am unsure which appointment to choose?",
        a: "In a live clinic, reception could help explain the types of appointment available. For this demo, choose any area of care to explore the form; it does not assess symptoms or recommend treatment.",
      },
      {
        q: "Can I mention access or communication needs?",
        a: "A real clinic should make it clear how to discuss access and communication preferences before a visit. This demo does not collect those details. They could be discussed directly with the clinic once a live service is configured.",
      },
      {
        q: "Can I get medical advice here?",
        a: "This is a website demonstration, not a clinical service. It cannot provide medical advice or respond to urgent requests. For a medical concern, contact an appropriate healthcare professional; for an emergency, use local emergency services.",
      },
    ],
  },
  contact: {
    eyebrow: "A place for a conversation",
    title: "Find your way\nto a first visit.",
    text: "In a live clinic website, this is where visitors would find the reception details, opening hours, and practical information for their visit.",
    addressLabel: "Illustrative location",
    address: "Garden Quarter, Baghdad, Iraq",
    emailLabel: "Example reception email",
    email: "hello@nawa.example",
    hoursLabel: "Example opening hours",
    hours: [
      { days: "Saturday – Thursday", time: "09:00 – 18:00" },
      { days: "Friday", time: "Closed" },
    ],
    link: "Try the booking form",
  },
  footer: {
    tagline: "Considered care. Human connections.",
    note: "Nawa is a fictional clinic. This template does not provide medical services or create appointments.",
    back: "Back to the top",
    credit: "A website concept by DevsHub.cc",
  },
};

export type ClinicContent = typeof en;

const ar: ClinicContent = {
  brand: "عيادة نواة",
  brandSub: "رعاية تبدأ بالاهتمام",
  demoLabel: "عيادة افتراضية · موقع تجريبي",
  nav: {
    care: "مجالات الرعاية",
    team: "الفريق",
    journey: "زيارتك",
    faq: "الأسئلة",
  },
  cta: "جرّب الحجز",
  hero: {
    eyebrow: "وقتٌ أكثر. وفهمٌ أقرب.",
    title: "رعاية تبدأ",
    accent: "بالإنصات إليك.",
    text: "مساحة لأسئلتك، ولصحتك اليومية، ولحديث واضح عن الخطوة القادمة. تعرّف على نهج في الرعاية يمنح التفاصيل حقّها من الاهتمام.",
    primary: "خطّط لزيارة أولى",
    secondary: "تعرّف على مجالات الرعاية",
    imageAlt: "تصوّر لاستقبال عيادة بخشب دافئ وإضاءة طبيعية وجلسات هادئة",
    imageLabel: "بداية أكثر هدوءاً",
    imageText: "وقتٌ للتأنّي. ومساحةٌ للحديث.",
    detail: "لصحتك اليومية، وللأسئلة التي ترافقها.",
  },
  principles: [
    { title: "وقت للإنصات", text: "نبدأ بما يشغلك وما يهمّك." },
    { title: "رعاية واضحة", text: "تعرّف على الخيارات والخطوات القادمة." },
    { title: "خطة نناقشها معاً", text: "مساحة لاحتياجاتك وتفضيلاتك." },
  ],
  care: {
    eyebrow: "كيف يمكننا مساعدتك",
    title: "رعاية يومية.\nواهتمام بك أنت.",
    text: "من الحديث الأول إلى زيارة المتابعة، تعرّف على نوع الموعد الذي يناسب سؤالك.",
    link: "ناقش زيارة",
    items: [
      {
        id: "general",
        icon: "stethoscope",
        title: "الطب العام",
        tag: "نقطة للبداية",
        text: "ناقش ما استجدّ من أسئلة، أو تحدّث عن صحتك العامة، أو راجع خطة رعاية مستمرة مع الطبيب.",
        detail: "استشارات · زيارات متابعة",
      },
      {
        id: "dental",
        icon: "smile",
        title: "طب الأسنان",
        tag: "اهتمام بالتفاصيل",
        text: "حديث عن صحة الأسنان واللثة، وفحوص دورية، وشرح واضح للخيارات العلاجية المتاحة.",
        detail: "فحص الأسنان · تخطيط الرعاية",
      },
      {
        id: "skin",
        icon: "sun",
        title: "صحة البشرة",
        tag: "مساحة لأسئلتك",
        text: "ناقش ما يشغلك بشأن بشرتك وما ترغب بفهمه. تعرّف على نهج للرعاية يستند إلى تقييم حالتك.",
        detail: "استشارات البشرة · المراجعات",
      },
      {
        id: "movement",
        icon: "activity",
        title: "الحركة والتأهيل",
        tag: "حركة تناسب حياتك",
        text: "تحدّث عن صعوبات الحركة، وأنشطتك اليومية، والأهداف التي تودّ العمل على تحقيقها.",
        detail: "العلاج الطبيعي · رعاية المتابعة",
      },
    ],
  },
  approach: {
    eyebrow: "نهجنا في الرعاية",
    title: "تأتي بأسئلتك.\nونمنحها وقتها.",
    text: "تبدأ الزيارة المفيدة بحوار. نفهم أولوياتك، ونوضّح الخيارات المتاحة، ثم نناقش معاً خطوة تالية تناسب ما تحتاجه.",
    note: "لا يوجد سؤال أصغر من أن يُطرح.",
    labels: ["نستمع", "نفهم", "نخطّط معاً"],
  },
  team: {
    eyebrow: "أشخاص وراء الرعاية",
    title: "فريق يهتمّ.\nوحديث قريب منك.",
    text: "مجالات رعاية مختلفة، وبداية مشتركة: الإنصات إلى الشخص الذي أمامنا.",
    demoNote: "شخصيات توضيحية لفريق هذه العيادة الافتراضية.",
    label: "مجال الاهتمام",
    members: [
      {
        id: "lina",
        initials: "ل ن",
        name: "د. لينا نادر",
        role: "الطب العام",
        focus: "الزيارات الأولى والرعاية المستمرة",
        bio: "نقطة بداية لأسئلة الصحة اليومية، وللحديث عن رعاية المتابعة.",
      },
      {
        id: "adam",
        initials: "آ س",
        name: "د. آدم سالم",
        role: "طب الأسنان",
        focus: "فحص الأسنان وتخطيط الرعاية",
        bio: "حديث قريب عن صحة الفم، والخيارات المتاحة، وما تحتاجه الزيارة القادمة.",
      },
      {
        id: "maya",
        initials: "م ع",
        name: "د. مايا عمر",
        role: "صحة البشرة",
        focus: "الاستشارات والمراجعات",
        bio: "وقت لمناقشة ما يشغلك بشأن بشرتك، وفهم التقييم، وطرح أسئلتك.",
      },
    ],
  },
  journey: {
    eyebrow: "قبل زيارتك الأولى",
    title: "طريق واضح،\nخطوة بخطوة.",
    text: "حين تعرف ما تتوقّعه، يصبح المكان الجديد أكثر ألفة. هكذا يمكن أن تسير الزيارة.",
    link: "استكشف تجربة الحجز",
    steps: [
      {
        title: "اختر نقطة البداية",
        text: "حدّد مجال الرعاية والفترة التي تفضّلها. في عيادة فعلية، يتولّى فريق الاستقبال تأكيد التفاصيل معك.",
      },
      {
        title: "امنح الحديث مساحته",
        text: "شارك الأسئلة التي تريد مناقشتها. الموعد فرصة أيضاً لفهم الخيارات المتاحة لك.",
      },
      {
        title: "افهم الخطوة التالية",
        text: "ناقش الخطة والمتابعة وطريقة طرح أي أسئلة لاحقة. خذ وقتك في طلب توضيح كل ما تحتاج إلى فهمه.",
      },
    ],
  },
  booking: {
    eyebrow: "خطوتك القادمة",
    title: "لنمنح زيارتك\nمساحتها.",
    text: "جرّب طلب موعد بخطوات بسيطة. اختر مجال الرعاية والفترة المناسبة لك لتتعرّف على طريقة عمل النموذج.",
    privacy: "استخدم بيانات وهمية فقط. لا تُدخل أي معلومات طبية.",
    formTitle: "جرّب طلب موعد",
    demoLabel: "حجز تجريبي",
    fields: {
      name: "اسمك",
      namePlaceholder: "اسم تجريبي",
      email: "البريد الإلكتروني",
      emailPlaceholder: "name@example.com",
      care: "مجال الرعاية",
      carePlaceholder: "اختر المجال",
      time: "الفترة المفضّلة",
      timePlaceholder: "اختر الفترة",
      timeOptions: ["صباحاً", "بعد الظهر", "لا تفضيل محدّد"],
    },
    submit: "معاينة طلبي",
    note: "للتجربة فقط. لا يتم إرسال أو حجز أي شيء.",
    success: {
      title: "أكملت تجربة الحجز",
      text: "لم يُنشأ أي موعد ولم تُرسل أي معلومات. هذه معاينة لشاشة التأكيد التي يراها زائر القالب.",
      again: "جرّب طلباً آخر",
    },
  },
  faq: {
    eyebrow: "معلومات قبل الخطوة الأولى",
    title: "أسئلة شائعة.\nوإجابات واضحة.",
    text: "بعض الوضوح قبل أن تختار خطوتك التالية.",
    items: [
      {
        q: "هل نواة عيادة حقيقية؟",
        a: "نواة علامة افتراضية أُنشئت لعرض هذا القالب. مجالات الرعاية وشخصيات الفريق والموقع وساعات العمل معلومات توضيحية. لا تُقدَّم أي خدمات طبية عبر هذه الصفحة.",
      },
      {
        q: "هل ينشئ النموذج موعداً فعلياً؟",
        a: "لا. يتيح لك تجربة الحقول ومشاهدة شاشة التأكيد فقط. لا تُرسل البيانات ولا تُحفظ كحجز ولا تُشارك مع عيادة. يُرجى استخدام بيانات وهمية فقط.",
      },
      {
        q: "ماذا لو لم أعرف نوع الموعد المناسب؟",
        a: "في عيادة فعلية، يمكن لفريق الاستقبال توضيح أنواع المواعيد المتاحة. في هذا العرض، اختر أي مجال لتجربة النموذج؛ فهو لا يقيّم الأعراض ولا يقترح علاجاً.",
      },
      {
        q: "هل يمكن مناقشة احتياجات الوصول أو التواصل؟",
        a: "من المفترض أن توضّح العيادة الفعلية طريقة مناقشة تفضيلات الوصول والتواصل قبل الزيارة. هذا العرض لا يجمع تلك التفاصيل. يمكن مناقشتها مباشرة مع العيادة عند إعداد خدمة فعلية.",
      },
      {
        q: "هل يمكن الحصول على نصيحة طبية هنا؟",
        a: "هذا عرض لموقع إلكتروني وليس خدمة صحية. لا يقدّم نصائح طبية ولا يستجيب للطلبات العاجلة. للاستفسارات الطبية تواصل مع مختص مناسب، وللطوارئ استخدم خدمات الطوارئ المحلية.",
      },
    ],
  },
  contact: {
    eyebrow: "مكان لبداية الحديث",
    title: "تعرّف على الطريق\nإلى زيارتك الأولى.",
    text: "في موقع عيادة فعلية، يجد الزائر هنا معلومات الاستقبال وساعات العمل والتفاصيل العملية التي يحتاجها قبل الزيارة.",
    addressLabel: "موقع توضيحي",
    address: "حي الحدائق، بغداد، العراق",
    emailLabel: "بريد استقبال توضيحي",
    email: "hello@nawa.example",
    hoursLabel: "ساعات عمل توضيحية",
    hours: [
      { days: "السبت – الخميس", time: "09:00 – 18:00" },
      { days: "الجمعة", time: "مغلق" },
    ],
    link: "جرّب نموذج الحجز",
  },
  footer: {
    tagline: "رعاية باهتمام. وتواصل إنساني.",
    note: "نواة عيادة افتراضية. لا يقدّم هذا القالب خدمات طبية ولا ينشئ مواعيد فعلية.",
    back: "العودة إلى الأعلى",
    credit: "تصوّر لموقع من DevsHub.cc",
  },
};

export const clinicContent: Record<DemoLang, ClinicContent> = { ar, en };
