import type { DemoLang } from "@/demos/config";

const en = {
  brand: "Dar Realty",
  brandSub: "Buy · Sell · Rent",
  nav: { listings: "Listings", areas: "Areas", agents: "Agents", about: "Why Dar", contact: "Contact" },
  cta: "Free valuation",
  hero: {
    eyebrow: "Baghdad · Erbil · Basra",
    title: "Find the home",
    titleAccent: "that fits your life.",
    text: "Verified listings, honest pricing and agents who answer their phones. Over 1,400 properties sold and rented since 2015.",
    search: {
      type: "Type",
      types: ["Apartment", "House", "Villa", "Land", "Office"],
      area: "Area",
      areas: ["Al-Mansour", "Al-Jadriya", "Zayouna", "Erbil — Dream City", "Basra — Al-Ashar"],
      budget: "Max budget",
      budgets: ["$100k", "$200k", "$350k", "$500k", "$1M+"],
      submit: "Search",
    },
    stats: [
      { value: "+1,400", label: "Properties closed" },
      { value: "320", label: "Active listings" },
      { value: "9", label: "Years" },
    ],
  },
  listings: {
    eyebrow: "Featured listings",
    title: "Hand-picked this week",
    text: "Every listing is visited and photographed by our team, with verified ownership documents.",
    all: "View all listings",
    labels: { beds: "beds", baths: "baths", area: "m²", sale: "For sale", rent: "For rent", month: "/ month", details: "Details" },
    items: [
      { title: "Modern villa with garden", location: "Al-Mansour, Baghdad", price: "$420,000", mode: "sale", beds: 5, baths: 4, area: 380, image: "/demos/art/property-01.svg", badge: "New" },
      { title: "Two-bedroom apartment, tower view", location: "Al-Jadriya, Baghdad", price: "$1,100", mode: "rent", beds: 2, baths: 2, area: 125, image: "/demos/art/property-02.svg", badge: "" },
      { title: "Townhouse in a gated compound", location: "Dream City, Erbil", price: "$265,000", mode: "sale", beds: 4, baths: 3, area: 240, image: "/demos/art/property-03.svg", badge: "Hot" },
      { title: "Penthouse with river view", location: "Abu Nuwas, Baghdad", price: "$690,000", mode: "sale", beds: 3, baths: 3, area: 290, image: "/demos/art/property-04.svg", badge: "Exclusive" },
      { title: "Farmhouse on 2,000 m²", location: "Al-Taji, Baghdad", price: "$310,000", mode: "sale", beds: 4, baths: 3, area: 310, image: "/demos/art/property-05.svg", badge: "" },
      { title: "Office floor, fitted", location: "Al-Ashar, Basra", price: "$2,400", mode: "rent", beds: 0, baths: 2, area: 420, image: "/demos/art/property-06.svg", badge: "" },
    ],
  },
  areas: {
    eyebrow: "Areas we know",
    title: "Neighbourhood guides",
    items: [
      { name: "Al-Mansour", text: "Embassies, schools and Baghdad's best restaurants.", count: "84 listings" },
      { name: "Al-Jadriya", text: "University district on the river, quiet streets.", count: "52 listings" },
      { name: "Zayouna", text: "Family compounds and new mid-rise towers.", count: "61 listings" },
      { name: "Erbil — Dream City", text: "Gated living, international schools, fast growth.", count: "47 listings" },
    ],
  },
  about: {
    eyebrow: "Why Dar",
    title: "Real estate, without the guesswork",
    points: [
      { title: "Verified ownership", text: "We check the title deed at the registry before a listing goes live." },
      { title: "Fair pricing", text: "Valuations based on real closed deals in the same street, not asking prices." },
      { title: "Legal hand-holding", text: "Contract drafting and registry appointments handled by our in-house lawyer." },
      { title: "After the keys", text: "Renovation, furnishing and property management for landlords abroad." },
    ],
  },
  agents: {
    eyebrow: "Agents",
    title: "People who know every street",
    items: [
      { name: "Mustafa Al-Jubouri", role: "Founder · Baghdad", deals: "410 deals", photo: "/demos/art/portrait-agent-1.svg" },
      { name: "Shilan Rasool", role: "Erbil office", deals: "230 deals", photo: "/demos/art/portrait-agent-2.svg" },
      { name: "Haider Naji", role: "Basra office", deals: "180 deals", photo: "/demos/art/portrait-agent-3.svg" },
    ],
    call: "Call",
  },
  process: {
    eyebrow: "Selling with Dar",
    title: "From valuation to keys in four steps",
    steps: [
      { title: "Free valuation", text: "A visit and a written price range within 48 hours." },
      { title: "Listing", text: "Professional photos, floor plan and promotion on all major portals." },
      { title: "Viewings & offers", text: "We qualify buyers and negotiate on your behalf." },
      { title: "Contract & registry", text: "Paperwork, payment escrow and the registry appointment." },
    ],
  },
  testimonials: {
    eyebrow: "Clients",
    title: "Trusted with the biggest decision",
    items: [
      { quote: "Sold our house in Mansour in three weeks, above the price two other agencies suggested.", name: "Sarmad & Rana", role: "Sellers, Baghdad" },
      { quote: "As a buyer from abroad, the video viewings and legal checks gave me confidence to sign.", name: "Dr. Ammar K.", role: "Buyer, London" },
      { quote: "They manage my two apartments and the rent arrives on the first of every month.", name: "Ali H.", role: "Landlord" },
    ],
  },
  contact: {
    eyebrow: "Valuation",
    title: "How much is your property worth?",
    text: "Fill in the basics and an agent will call to arrange a free visit.",
    fields: {
      name: "Name",
      phone: "Phone",
      type: "Property type",
      typePh: "Choose type",
      area: "Area",
      areaPh: "Choose area",
      size: "Size (m²)",
      goal: "I want to",
      goals: ["Sell", "Rent out", "Buy", "Rent"],
      notes: "Details",
      notesPh: "Floor, finishing, parking, anything special…",
    },
    submit: "Request valuation",
    success: { title: "Request received", text: "An agent will call you within one business day.", again: "Send another request" },
    note: "Demo form — nothing is actually sent.",
    address: "Al-Mansour, Princesses Street, Baghdad",
    phone: "+964 781 000 0000",
    hours: "Sat–Thu 9:00–19:00",
    labels: { address: "Office", phone: "Phone", hours: "Hours" },
  },
  footer: { tagline: "Licensed real-estate agency in Baghdad, Erbil and Basra.", rights: "All rights reserved." },
};

export type RealEstateContent = typeof en;

const ar: RealEstateContent = {
  brand: "دار العقارية",
  brandSub: "بيع · شراء · إيجار",
  nav: { listings: "العقارات", areas: "المناطق", agents: "الوكلاء", about: "لماذا دار", contact: "تواصل" },
  cta: "تقييم مجاني",
  hero: {
    eyebrow: "بغداد · أربيل · البصرة",
    title: "ابحث عن البيت",
    titleAccent: "الذي يناسب حياتك.",
    text: "عقارات موثّقة، أسعار صادقة، ووكلاء يردّون على الهاتف. أكثر من 1,400 عقار بيع وأُجّر منذ 2015.",
    search: {
      type: "النوع",
      types: ["شقة", "بيت", "فيلا", "أرض", "مكتب"],
      area: "المنطقة",
      areas: ["المنصور", "الجادرية", "زيونة", "أربيل — دريم سيتي", "البصرة — العشار"],
      budget: "الميزانية القصوى",
      budgets: ["100 ألف $", "200 ألف $", "350 ألف $", "500 ألف $", "+1 مليون $"],
      submit: "بحث",
    },
    stats: [
      { value: "+1,400", label: "صفقة مكتملة" },
      { value: "320", label: "عقار متاح" },
      { value: "9", label: "سنوات" },
    ],
  },
  listings: {
    eyebrow: "عقارات مميزة",
    title: "مختارات هذا الأسبوع",
    text: "كل عقار يزوره فريقنا ويصوّره، مع التحقق من مستندات الملكية.",
    all: "كل العقارات",
    labels: { beds: "غرف", baths: "حمامات", area: "م²", sale: "للبيع", rent: "للإيجار", month: "/ شهرياً", details: "التفاصيل" },
    items: [
      { title: "فيلا حديثة مع حديقة", location: "المنصور، بغداد", price: "$420,000", mode: "sale", beds: 5, baths: 4, area: 380, image: "/demos/art/property-01.svg", badge: "جديد" },
      { title: "شقة غرفتين بإطلالة برجية", location: "الجادرية، بغداد", price: "$1,100", mode: "rent", beds: 2, baths: 2, area: 125, image: "/demos/art/property-02.svg", badge: "" },
      { title: "تاون هاوس في مجمع مسوّر", location: "دريم سيتي، أربيل", price: "$265,000", mode: "sale", beds: 4, baths: 3, area: 240, image: "/demos/art/property-03.svg", badge: "مطلوب" },
      { title: "بنتهاوس بإطلالة على النهر", location: "أبو نؤاس، بغداد", price: "$690,000", mode: "sale", beds: 3, baths: 3, area: 290, image: "/demos/art/property-04.svg", badge: "حصري" },
      { title: "مزرعة على 2,000 م²", location: "التاجي، بغداد", price: "$310,000", mode: "sale", beds: 4, baths: 3, area: 310, image: "/demos/art/property-05.svg", badge: "" },
      { title: "طابق مكتبي مجهّز", location: "العشار، البصرة", price: "$2,400", mode: "rent", beds: 0, baths: 2, area: 420, image: "/demos/art/property-06.svg", badge: "" },
    ],
  },
  areas: {
    eyebrow: "مناطق نعرفها",
    title: "دليل الأحياء",
    items: [
      { name: "المنصور", text: "السفارات والمدارس وأفضل مطاعم بغداد.", count: "84 عقاراً" },
      { name: "الجادرية", text: "حي الجامعة على النهر، شوارع هادئة.", count: "52 عقاراً" },
      { name: "زيونة", text: "مجمعات عائلية وأبراج جديدة متوسطة الارتفاع.", count: "61 عقاراً" },
      { name: "أربيل — دريم سيتي", text: "سكن مسوّر، مدارس دولية، نمو سريع.", count: "47 عقاراً" },
    ],
  },
  about: {
    eyebrow: "لماذا دار",
    title: "عقارات بلا تخمين",
    points: [
      { title: "ملكية موثّقة", text: "نتحقق من سند الملكية في دائرة التسجيل قبل نشر أي عقار." },
      { title: "تسعير عادل", text: "تقييمات مبنية على صفقات حقيقية مكتملة في الشارع نفسه، لا على أسعار العرض." },
      { title: "مرافقة قانونية", text: "صياغة العقود ومواعيد التسجيل العقاري بإشراف محامي المكتب." },
      { title: "ما بعد المفاتيح", text: "ترميم وتأثيث وإدارة أملاك للمالكين خارج العراق." },
    ],
  },
  agents: {
    eyebrow: "الوكلاء",
    title: "أشخاص يعرفون كل شارع",
    items: [
      { name: "مصطفى الجبوري", role: "المؤسس · بغداد", deals: "410 صفقات", photo: "/demos/art/portrait-agent-1.svg" },
      { name: "شيلان رسول", role: "مكتب أربيل", deals: "230 صفقة", photo: "/demos/art/portrait-agent-2.svg" },
      { name: "حيدر ناجي", role: "مكتب البصرة", deals: "180 صفقة", photo: "/demos/art/portrait-agent-3.svg" },
    ],
    call: "اتصال",
  },
  process: {
    eyebrow: "البيع مع دار",
    title: "من التقييم إلى المفاتيح في أربع خطوات",
    steps: [
      { title: "تقييم مجاني", text: "زيارة ونطاق سعر مكتوب خلال 48 ساعة." },
      { title: "النشر", text: "صور احترافية ومخطط وترويج على كل المنصات الكبرى." },
      { title: "المعاينات والعروض", text: "نفرز المشترين الجادين ونتفاوض نيابةً عنك." },
      { title: "العقد والتسجيل", text: "الأوراق وضمان الدفع وموعد دائرة التسجيل." },
    ],
  },
  testimonials: {
    eyebrow: "العملاء",
    title: "ثقة في أكبر قرار",
    items: [
      { quote: "باعوا بيتنا في المنصور خلال ثلاثة أسابيع، وبسعر أعلى مما اقترحه مكتبان آخران.", name: "سرمد ورنا", role: "بائعان، بغداد" },
      { quote: "كمشترٍ من الخارج، المعاينات بالفيديو والفحوصات القانونية أعطتني الثقة للتوقيع.", name: "د. عمار ك.", role: "مشترٍ، لندن" },
      { quote: "يديرون شقتيّ ويصل الإيجار في أول كل شهر.", name: "علي ح.", role: "مالك" },
    ],
  },
  contact: {
    eyebrow: "التقييم",
    title: "كم يساوي عقارك؟",
    text: "أدخل المعلومات الأساسية وسيتصل بك وكيل لترتيب زيارة مجانية.",
    fields: {
      name: "الاسم",
      phone: "الهاتف",
      type: "نوع العقار",
      typePh: "اختر النوع",
      area: "المنطقة",
      areaPh: "اختر المنطقة",
      size: "المساحة (م²)",
      goal: "أريد",
      goals: ["البيع", "التأجير", "الشراء", "الاستئجار"],
      notes: "تفاصيل",
      notesPh: "الطابق، التشطيب، المواقف، أي ميزة خاصة…",
    },
    submit: "طلب تقييم",
    success: { title: "تم استلام طلبك", text: "سيتصل بك وكيل خلال يوم عمل واحد.", again: "إرسال طلب آخر" },
    note: "نموذج تجريبي — لا يتم إرسال أي بيانات.",
    address: "المنصور، شارع الأميرات، بغداد",
    phone: "+964 781 000 0000",
    hours: "السبت–الخميس 9:00–19:00",
    labels: { address: "المكتب", phone: "الهاتف", hours: "الدوام" },
  },
  footer: { tagline: "مكتب عقاري مرخّص في بغداد وأربيل والبصرة.", rights: "جميع الحقوق محفوظة." },
};

export const realestateContent: Record<DemoLang, RealEstateContent> = { ar, en };
