import type { RetailContent } from "../retail/types";
export const appliancesContent: Record<"en" | "ar", RetailContent> = {
  en: {
    brand: "MATIN",
    descriptor: "Considered living.",
    announcement: "A little more ease. In every corner of home.",
    nav: ["Collection", "Our approach", "Let’s talk"],
    hero: {
      eyebrow: "THE EVERYDAY, UPGRADED",
      title: "Made for life.",
      accent: "Chosen for home.",
      text: "Thoughtfully selected appliances that make room for what matters. Explore a quieter, simpler way to live.",
      primary: "Explore the collection",
      secondary: "Find your fit",
      imageAlt:
        "A refrigerator, washing machine and coffee maker in a warm, sunlit interior",
      caption: "Good design belongs in everyday life.",
    },
    benefits: [
      {
        title: "Details made clear",
        text: "Compare dimensions, capacity and everyday features.",
      },
      {
        title: "A considered selection",
        text: "Essentials for the kitchen, laundry and the spaces between.",
      },
      {
        title: "Guidance that helps",
        text: "Start with your space. We’ll help you build your shortlist.",
      },
    ],
    catalogue: {
      eyebrow: "THE COLLECTION",
      title: "A better everyday starts here.",
      text: "Explore illustrative products and specifications. All prices are for this demo only.",
      all: "All appliances",
      search: "Search appliances",
      searchPlaceholder: "Try washer, coffee or cooling…",
      sort: "Sort products",
      featured: "Our selection",
      low: "Price: low to high",
      high: "Price: high to low",
      results: "products",
      empty: "No appliances match your search.",
      reset: "Reset filters",
      details: "Explore details",
      add: "Add to shortlist",
      added: "Added to your shortlist",
      close: "Close",
      currency: "IQD",
      specTitle: "The details",
    },
    categories: [
      { id: "kitchen", name: "Kitchen" },
      { id: "laundry", name: "Laundry" },
      { id: "living", name: "Home comfort" },
    ],
    products: [
      {
        id: "cool-420",
        category: "kitchen",
        name: "Fresh 420 refrigerator",
        description:
          "Space for a full week, with thoughtful storage for the little things.",
        specs: [
          "420-litre illustrative capacity",
          "70 × 68 × 185 cm",
          "Adjustable glass shelves",
        ],
        price: 890000,
        visual: "fridge",
        color: "#B8C3B7",
      },
      {
        id: "wash-9",
        category: "laundry",
        name: "Quiet 9 washing machine",
        description:
          "A generous drum and a simple dial. An easier rhythm for laundry day.",
        specs: [
          "9 kg illustrative capacity",
          "60 × 60 × 85 cm",
          "Quick-wash programme",
        ],
        price: 675000,
        visual: "washer",
        color: "#D9DDD5",
      },
      {
        id: "bake-60",
        category: "kitchen",
        name: "Gather built-in oven",
        description: "From slow Sunday lunches to a quick dinner for two.",
        specs: [
          "60 cm built-in format",
          "65-litre illustrative cavity",
          "Fan-assisted cooking",
        ],
        price: 520000,
        visual: "oven",
        color: "#A2ADA5",
      },
      {
        id: "brew",
        category: "kitchen",
        name: "Morning coffee maker",
        description: "A familiar ritual, with a little more care in every cup.",
        specs: [
          "1.2-litre water tank",
          "Removable drip tray",
          "Compact countertop design",
        ],
        price: 185000,
        visual: "coffee",
        color: "#D8C6AB",
      },
      {
        id: "air-18",
        category: "living",
        name: "Breeze room cooling",
        description:
          "A clean profile designed to sit quietly within your room.",
        specs: [
          "Wall-mounted indoor unit",
          "Adjustable airflow",
          "Remote control included",
        ],
        price: 740000,
        visual: "ac",
        color: "#E4E3D8",
      },
      {
        id: "clean",
        category: "living",
        name: "Everyday cordless vacuum",
        description:
          "Lightweight, easy to reach for, and ready for the everyday.",
        specs: [
          "Cordless stick format",
          "Removable dust container",
          "Wall-mount storage",
        ],
        price: 245000,
        visual: "vacuum",
        color: "#8E9C8B",
      },
    ],
    story: {
      eyebrow: "LESS FRICTION. MORE LIVING.",
      title: "A home that works around you.",
      text: "The right appliance begins with understanding your day. Your kitchen layout. Your family’s routine. The things you want to spend less time doing.",
      points: [
        "Measure your space before you choose.",
        "Compare the features you’ll actually use.",
        "Plan delivery and installation together.",
      ],
      cta: "Let’s find the right fit",
    },
    guide: {
      eyebrow: "A SIMPLE PLACE TO START",
      title: "From a good choice to a good fit.",
      steps: [
        {
          title: "Know your space",
          text: "Check the opening, ventilation and route from the door to its final place.",
        },
        {
          title: "Build a shortlist",
          text: "Compare capacity, dimensions and the features that matter to your household.",
        },
        {
          title: "Ask the right questions",
          text: "Confirm availability, installation needs and written warranty terms before buying.",
        },
      ],
    },
    faqTitle: "A few useful answers.",
    faqs: [
      {
        question: "Can I buy the products shown here?",
        answer:
          "This is a fictional storefront demonstration. Products, specifications and prices illustrate the shopping experience; no orders or payments are processed.",
      },
      {
        question: "How does the shortlist work?",
        answer:
          "Add products, adjust quantities and review the total in your demo shortlist. It stays in this page session and is cleared when you reload.",
      },
      {
        question: "What should I check before replacing an appliance?",
        answer:
          "Measure the space and delivery route, check power and plumbing requirements, and confirm installation and warranty terms with the actual seller.",
      },
    ],
    contact: {
      eyebrow: "LET’S MAKE ROOM FOR BETTER",
      title: "Tell us about your home.",
      text: "A new kitchen, a first apartment or one small upgrade. Every good choice starts with a conversation.",
      name: "Your name",
      email: "Email address",
      message: "What are you looking for?",
      submit: "Try the enquiry form",
      note: "Demo only. Your details are not sent or stored.",
      success: {
        title: "That’s how your enquiry would look.",
        text: "This demo hasn’t sent or saved your details. A live store can connect this form to its sales team.",
        again: "Try another enquiry",
      },
    },
    cart: {
      title: "Your shortlist",
      empty: "A little inspiration starts with your first appliance.",
      subtotal: "Illustrative total",
      remove: "Remove",
      increase: "Increase quantity",
      decrease: "Decrease quantity",
      checkout: "Preview enquiry",
      note: "Demonstration only. Prices are illustrative; no purchase, payment or enquiry is sent.",
      done: "Your shortlist is ready.",
      doneText:
        "This is a preview of the enquiry step. Nothing has been ordered or sent.",
      continue: "Keep exploring",
      item: "shortlisted items",
    },
    footer:
      "MATIN is a fictional appliance brand created to demonstrate a retail website.",
    top: "Back to top",
  },
  ar: {
    brand: "متين",
    descriptor: "للأجهزة المنزلية",
    announcement: "راحة أكثر. في كل زاوية من البيت.",
    nav: ["الأجهزة", "طريقتنا", "تواصل ويانا"],
    hero: {
      eyebrow: "تفاصيل صغيرة. يوم أجمل.",
      title: "مصمّمة للحياة.",
      accent: "مختارة لبيتك.",
      text: "أجهزة مختارة بعناية، تسهّل يومك وتترك لك وقت للأشياء اللي تحبّها. اكتشف راحة تناسب بيتك وطريقتك بالحياة.",
      primary: "استكشف الأجهزة",
      secondary: "اختار اللي يناسبك",
      imageAlt: "ثلاجة وغسالة وماكينة قهوة في مساحة منزلية دافئة مضاءة بالشمس",
      caption: "التصميم الحلو مكانه بحياتنا اليومية.",
    },
    benefits: [
      {
        title: "تفاصيل واضحة",
        text: "قارن الأحجام والسعات والخصائص اللي تحتاجها كل يوم.",
      },
      {
        title: "اختيارات مدروسة",
        text: "أساسيات المطبخ والغسيل وراحة البيت، بمكان واحد.",
      },
      {
        title: "مساعدة تفيدك",
        text: "نبدأ من مساحة بيتك ونساعدك ترتّب اختياراتك.",
      },
    ],
    catalogue: {
      eyebrow: "مجموعتنا",
      title: "يوم أسهل يبدأ من هنا.",
      text: "منتجات ومواصفات توضيحية لتجربة القالب. كل الأسعار تجريبية فقط.",
      all: "كل الأجهزة",
      search: "ابحث عن جهاز",
      searchPlaceholder: "جرّب غسالة، قهوة أو تبريد…",
      sort: "ترتيب الأجهزة",
      featured: "اختياراتنا",
      low: "السعر: من الأقل للأعلى",
      high: "السعر: من الأعلى للأقل",
      results: "أجهزة",
      empty: "ماكو أجهزة تطابق بحثك.",
      reset: "إعادة ضبط الفلاتر",
      details: "شوف التفاصيل",
      add: "أضف لقائمة الاختيار",
      added: "تمت الإضافة لقائمتك",
      close: "إغلاق",
      currency: "د.ع",
      specTitle: "التفاصيل",
    },
    categories: [
      { id: "kitchen", name: "المطبخ" },
      { id: "laundry", name: "الغسيل" },
      { id: "living", name: "راحة البيت" },
    ],
    products: [
      {
        id: "cool-420",
        category: "kitchen",
        name: "ثلاجة فريش ٤٢٠",
        description:
          "مساحة تكفي احتياجات الأسبوع، وترتيب ذكي للتفاصيل الصغيرة.",
        specs: [
          "سعة توضيحية ٤٢٠ لتر",
          "٧٠ × ٦٨ × ١٨٥ سم",
          "رفوف زجاجية قابلة للتعديل",
        ],
        price: 890000,
        visual: "fridge",
        color: "#B8C3B7",
      },
      {
        id: "wash-9",
        category: "laundry",
        name: "غسالة كوايت ٩",
        description: "حوض واسع وتحكّم بسيط، حتى يصير يوم الغسيل أخف.",
        specs: ["سعة توضيحية ٩ كغم", "٦٠ × ٦٠ × ٨٥ سم", "برنامج غسيل سريع"],
        price: 675000,
        visual: "washer",
        color: "#D9DDD5",
      },
      {
        id: "bake-60",
        category: "kitchen",
        name: "فرن غاذر المدمج",
        description: "من غداء العائلة ليوم الجمعة إلى عشاء سريع لشخصين.",
        specs: [
          "تصميم مدمج بعرض ٦٠ سم",
          "سعة توضيحية ٦٥ لتر",
          "توزيع حرارة بالمروحة",
        ],
        price: 520000,
        visual: "oven",
        color: "#A2ADA5",
      },
      {
        id: "brew",
        category: "kitchen",
        name: "ماكينة قهوة مورنينغ",
        description: "طقس الصباح المعتاد، بعناية أكثر بكل فنجان.",
        specs: [
          "خزان ماء ١٫٢ لتر",
          "صينية تقطير قابلة للإزالة",
          "حجم مناسب لطاولة المطبخ",
        ],
        price: 185000,
        visual: "coffee",
        color: "#D8C6AB",
      },
      {
        id: "air-18",
        category: "living",
        name: "مكيّف بريز",
        description: "تصميم هادئ ينسجم مع غرفتك وتفاصيلها.",
        specs: [
          "وحدة داخلية تثبّت على الجدار",
          "توجيه هواء قابل للتعديل",
          "جهاز تحكّم مرفق",
        ],
        price: 740000,
        visual: "ac",
        color: "#E4E3D8",
      },
      {
        id: "clean",
        category: "living",
        name: "مكنسة إڤريداي اللاسلكية",
        description: "خفيفة، سهلة الاستخدام، وجاهزة لتفاصيل اليوم العادية.",
        specs: [
          "تصميم عصا لاسلكي",
          "حاوية غبار قابلة للإزالة",
          "حامل تخزين جداري",
        ],
        price: 245000,
        visual: "vacuum",
        color: "#8E9C8B",
      },
    ],
    story: {
      eyebrow: "شغل أقل. راحة أكثر.",
      title: "بيت يشتغل على راحتك.",
      text: "اختيار الجهاز الصح يبدأ من فهم يومك: توزيع المطبخ، روتين العائلة، والشغلات اللي تريد تخلّصها بوقت أقل.",
      points: [
        "قِس المساحة قبل الاختيار.",
        "قارن الخصائص اللي فعلاً تستخدمها.",
        "رتّب التوصيل والتركيب سوا.",
      ],
      cta: "خلّ نختار المناسب",
    },
    guide: {
      eyebrow: "بداية بسيطة",
      title: "من اختيار حلو إلى مكانه الصح.",
      steps: [
        {
          title: "اعرف مساحتك",
          text: "قِس الفتحة والتهوية والطريق من باب البيت إلى مكان الجهاز.",
        },
        {
          title: "رتّب اختياراتك",
          text: "قارن السعة والأبعاد والخصائص اللي تهم أهل البيت.",
        },
        {
          title: "اسأل قبل ما تشتري",
          text: "تأكد من التوفر ومتطلبات التركيب وشروط الكفالة المكتوبة من البائع.",
        },
      ],
    },
    faqTitle: "كم جواب يفيدك.",
    faqs: [
      {
        question: "أكدر أشتري الأجهزة الموجودة هنا؟",
        answer:
          "هذا نموذج توضيحي لمتجر افتراضي. المنتجات والمواصفات والأسعار لعرض تجربة التسوّق فقط، وماكو طلبات أو مدفوعات حقيقية.",
      },
      {
        question: "شلون تشتغل قائمة الاختيار؟",
        answer:
          "أضف الأجهزة وعدّل الكميات وراجع المجموع التجريبي. القائمة تبقى خلال جلسة الصفحة الحالية وتُمسح عند إعادة تحميلها.",
      },
      {
        question: "شنو أتأكد منه قبل أبدّل جهاز؟",
        answer:
          "قِس المساحة وطريق التوصيل، وتحقق من متطلبات الكهرباء والماء وشروط التركيب والكفالة عند البائع الفعلي.",
      },
    ],
    contact: {
      eyebrow: "خلّ نسوي مساحة للأفضل",
      title: "احچيلنا عن بيتك.",
      text: "مطبخ جديد، أول شقة، أو تغيير بسيط. كل اختيار موفق يبدأ بمحادثة.",
      name: "اسمك",
      email: "البريد الإلكتروني",
      message: "شنو الجهاز اللي تدور عليه؟",
      submit: "جرّب نموذج الاستفسار",
      note: "للتجربة فقط. بياناتك ما تنرسل ولا تنخزن.",
      success: {
        title: "هيچ راح يكون استفسارك.",
        text: "النموذج ما أرسل ولا حفظ بياناتك. بالمتجر الفعلي نكدر نربطه بفريق المبيعات.",
        again: "جرّب استفسار ثاني",
      },
    },
    cart: {
      title: "قائمة اختياراتك",
      empty: "ابدأ بأول جهاز يناسب بيتك.",
      subtotal: "المجموع التوضيحي",
      remove: "حذف",
      increase: "زيادة الكمية",
      decrease: "تقليل الكمية",
      checkout: "معاينة الاستفسار",
      note: "للعرض فقط. الأسعار توضيحية، وماكو شراء أو دفع أو إرسال استفسار.",
      done: "قائمة اختياراتك جاهزة.",
      doneText: "هذه معاينة لخطوة الاستفسار. ما تم طلب أو إرسال أي شيء.",
      continue: "كمّل استكشاف",
      item: "أجهزة بالقائمة",
    },
    footer:
      "متين علامة افتراضية للأجهزة المنزلية، صُممت لعرض نموذج متجر إلكتروني.",
    top: "الرجوع للأعلى",
  },
};
