import type { DemoLang } from "@/demos/config";

const en = {
  brand: "PULSE",
  brandSub: "TRAINING CLUB",
  nav: {
    zones: "The floor",
    schedule: "Classes",
    plans: "Membership",
    coaches: "Coaching",
  },
  cta: "Find your plan",
  eyebrow: "A DIFFERENT KIND OF EVERYDAY",
  hero: {
    first: "SHOW UP.",
    second: "FIND YOUR",
    third: "PULSE.",
    text: "A floor for lifting. Space to move. A session worth showing up for. Make training part of your week, on your terms.",
    primary: "Explore membership",
    secondary: "See the timetable",
    artLabel: "THE STRENGTH FLOOR",
    artCaption: "Less noise. More movement.",
    tag: "STRENGTH / CONDITIONING / MOBILITY",
  },
  strip: ["COME AS YOU ARE", "TRAIN WITH INTENT", "FIND YOUR RHYTHM"],
  zones: {
    eyebrow: "01 / YOUR TRAINING GROUND",
    title: "ONE FLOOR.\nMORE WAYS TO MOVE.",
    text: "Choose the space that fits today's session. These areas illustrate how a real club could introduce its facilities.",
    items: [
      {
        title: "The strength floor",
        label: "LIFT",
        text: "Free weights, racks and room to focus on the next set.",
        detail: "Racks · Dumbbells · Benches",
      },
      {
        title: "The engine room",
        label: "MOVE",
        text: "A flexible space for intervals, circuits and group sessions.",
        detail: "Sled track · Bikes · Open floor",
      },
      {
        title: "The reset zone",
        label: "RESET",
        text: "A quieter corner for mobility, stretching and a slower finish.",
        detail: "Mats · Bands · Mobility tools",
      },
    ],
  },
  schedule: {
    eyebrow: "02 / MAKE ROOM IN YOUR WEEK",
    title: "YOUR NEXT SESSION.",
    text: "Filter the sample timetable by day and training style. Times and sessions are illustrative.",
    dayLabel: "Choose a day",
    typeLabel: "Training style",
    all: "All styles",
    days: [
      { id: "sat", label: "Saturday" },
      { id: "sun", label: "Sunday" },
      { id: "mon", label: "Monday" },
      { id: "tue", label: "Tuesday" },
      { id: "wed", label: "Wednesday" },
      { id: "thu", label: "Thursday" },
    ],
    types: [
      { id: "strength", label: "Strength" },
      { id: "conditioning", label: "Conditioning" },
      { id: "mobility", label: "Mobility" },
    ],
    empty: "No sample sessions match these filters. Try another day or style.",
    result: "Sessions shown",
    join: "Try this session",
    duration: "minutes",
    sessions: [
      {
        id: "s1",
        day: "sat",
        type: "strength",
        time: "07:00",
        title: "Strength foundations",
        minutes: 50,
        level: "All levels",
      },
      {
        id: "s2",
        day: "sat",
        type: "conditioning",
        time: "18:30",
        title: "The circuit",
        minutes: 45,
        level: "Choose your pace",
      },
      {
        id: "s3",
        day: "sun",
        type: "mobility",
        time: "08:00",
        title: "Move & reset",
        minutes: 40,
        level: "All levels",
      },
      {
        id: "s4",
        day: "sun",
        type: "strength",
        time: "19:00",
        title: "Lift together",
        minutes: 50,
        level: "All levels",
      },
      {
        id: "s5",
        day: "mon",
        type: "conditioning",
        time: "18:00",
        title: "Engine club",
        minutes: 45,
        level: "Choose your pace",
      },
      {
        id: "s6",
        day: "tue",
        type: "strength",
        time: "07:00",
        title: "Strength foundations",
        minutes: 50,
        level: "All levels",
      },
      {
        id: "s7",
        day: "wed",
        type: "mobility",
        time: "18:30",
        title: "Move & reset",
        minutes: 40,
        level: "All levels",
      },
      {
        id: "s8",
        day: "thu",
        type: "conditioning",
        time: "17:00",
        title: "The circuit",
        minutes: 45,
        level: "Choose your pace",
      },
    ],
  },
  plans: {
    eyebrow: "03 / YOUR WEEK. YOUR MEMBERSHIP.",
    title: "CHOOSE YOUR RHYTHM.",
    text: "Three sample memberships. Illustrative monthly prices in Iraqi dinars; no payment or subscription is created on this demo.",
    currency: "IQD",
    period: "/ month",
    choose: "Choose this plan",
    selected: "Selected plan",
    popular: "THE MIDDLE GROUND",
    items: [
      {
        id: "base",
        name: "BASE",
        price: "75,000",
        text: "For your own training routine.",
        features: [
          "Open-floor training",
          "Strength and mobility zones",
          "A first-visit introduction",
        ],
      },
      {
        id: "flow",
        name: "FLOW",
        price: "110,000",
        text: "Your routine, with a group rhythm.",
        features: [
          "Everything in Base",
          "Four group sessions per month",
          "Class timetable access",
        ],
      },
      {
        id: "all",
        name: "ALL IN",
        price: "155,000",
        text: "More space for a varied week.",
        features: [
          "Everything in Flow",
          "Unlimited sample group sessions",
          "One coaching conversation per month",
        ],
      },
    ],
  },
  coaches: {
    eyebrow: "04 / PEOPLE BEFORE PERSONAL BESTS",
    title: "A COACHING FLOOR.\nNOT A SPOTLIGHT.",
    text: "Ask a question. Talk through a movement. Find an approach that fits your experience. These illustrated roles show how a club can present its coaching team without invented portraits.",
    badge: "ILLUSTRATIVE COACHING ROLES",
    items: [
      {
        initials: "ST",
        title: "Strength coaching",
        role: "Technique · Session planning",
        text: "A conversation about your training experience and the session ahead.",
      },
      {
        initials: "MV",
        title: "Movement coaching",
        role: "Mobility · Group sessions",
        text: "Space to ask questions, explore movement and find your own pace.",
      },
    ],
  },
  faq: {
    eyebrow: "BEFORE YOU SHOW UP",
    title: "A FEW GOOD QUESTIONS.",
    items: [
      {
        q: "Do I need training experience?",
        a: "This concept welcomes different starting points. In a real club, speak with the team about your experience and which introduction would suit you before joining a session.",
      },
      {
        q: "Can I explore a class before choosing a plan?",
        a: "Yes. Use the timetable to choose a sample session, then open the trial form. On this demo, submitting it only displays a local confirmation.",
      },
      {
        q: "Are these real prices or memberships?",
        a: "No. The plans, prices and timetable are sample content. The form does not send data, take payment or create a membership.",
      },
      {
        q: "What should I bring to a first visit?",
        a: "Comfortable training clothes, suitable shoes, a water bottle and any questions for the team. Confirm the actual club's facilities and requirements when arranging a real visit.",
      },
    ],
  },
  contact: {
    eyebrow: "YOUR NEXT STEP",
    title: "START WITH\nSHOWING UP.",
    text: "Explore a first visit with this sample signup. No personal information is sent anywhere.",
    button: "Open the trial form",
    location: "Baghdad · Concept location",
    hoursLabel: "Sample opening hours",
    hours: "Saturday–Thursday / 06:00–23:00",
    note: "PULSE is a fictional training club. This is an interactive website concept, not a real gym booking service.",
    back: "Back to top",
  },
  form: {
    title: "PLAN YOUR FIRST VISIT.",
    intro:
      "Choose a sample plan and try the form. No booking, membership or payment will be created.",
    close: "Close signup",
    plan: "Sample membership",
    session: "Your sample session",
    name: "Your name",
    namePh: "Use a sample name",
    email: "Email",
    emailPh: "name@example.com",
    phone: "Phone (optional)",
    phonePh: "Example phone number",
    preference: "What would you like to explore?",
    preferencePh: "Choose a training area",
    submit: "Try the signup",
    note: "Demo only. Nothing is sent or charged.",
    success: {
      title: "That's the demo flow.",
      text: "Your sample form is complete. No data was sent, no booking was made and no payment was taken.",
      again: "Try the form again",
    },
  },
};
export type GymContent = typeof en;
const ar: GymContent = {
  brand: "نبض",
  brandSub: "نادي التدريب",
  nav: {
    zones: "مساحات التدريب",
    schedule: "الحصص",
    plans: "العضوية",
    coaches: "التوجيه",
  },
  cta: "اختر عضويتك",
  eyebrow: "إيقاع جديد ليومك",
  hero: {
    first: "ابدأ اليوم.",
    second: "واكتشف",
    third: "نبضك.",
    text: "مساحة للأوزان، وأخرى للحركة، وحصة تستحق أن تخصص لها وقتاً. اجعل التدريب جزءاً من أسبوعك بالطريقة التي تناسبك.",
    primary: "استكشف العضويات",
    secondary: "شاهد جدول الحصص",
    artLabel: "مساحة القوة",
    artCaption: "ضجيج أقل. حركة أكثر.",
    tag: "قوة / لياقة / مرونة",
  },
  strip: ["ابدأ من مكانك", "تدرّب بوضوح", "اكتشف إيقاعك"],
  zones: {
    eyebrow: "٠١ / مساحة لك",
    title: "مكان واحد.\nطرق أكثر للحركة.",
    text: "اختر المساحة التي تناسب تدريبك اليوم. هذه الأقسام توضح طريقة عرض مرافق نادٍ رياضي في موقعه.",
    items: [
      {
        title: "مساحة القوة",
        label: "ارفع",
        text: "أوزان حرة وحوامل ومقاعد، ومساحة للتركيز على مجموعتك التالية.",
        detail: "حوامل · أوزان حرة · مقاعد",
      },
      {
        title: "مساحة اللياقة",
        label: "تحرّك",
        text: "مساحة مرنة للتدريب المتقطع والدوائر والحصص الجماعية.",
        detail: "مسار دفع · دراجات · مساحة مفتوحة",
      },
      {
        title: "مساحة المرونة",
        label: "استعد",
        text: "ركن أهدأ لتمارين الحركة والإطالة وإنهاء التدريب بإيقاع أبطأ.",
        detail: "حصائر · أربطة · أدوات حركة",
      },
    ],
  },
  schedule: {
    eyebrow: "٠٢ / وقت للتدريب",
    title: "حصتك القادمة.",
    text: "صفِّ الجدول حسب اليوم ونوع التدريب. الحصص والمواعيد هنا للتوضيح فقط.",
    dayLabel: "اختر اليوم",
    typeLabel: "نوع التدريب",
    all: "جميع الأنواع",
    days: [
      { id: "sat", label: "السبت" },
      { id: "sun", label: "الأحد" },
      { id: "mon", label: "الاثنين" },
      { id: "tue", label: "الثلاثاء" },
      { id: "wed", label: "الأربعاء" },
      { id: "thu", label: "الخميس" },
    ],
    types: [
      { id: "strength", label: "قوة" },
      { id: "conditioning", label: "لياقة" },
      { id: "mobility", label: "مرونة" },
    ],
    empty: "لا توجد حصص نموذجية بهذه الخيارات. جرّب يوماً أو نوع تدريب آخر.",
    result: "الحصص المعروضة",
    join: "جرّب هذه الحصة",
    duration: "دقيقة",
    sessions: [
      {
        id: "s1",
        day: "sat",
        type: "strength",
        time: "07:00",
        title: "أساسيات القوة",
        minutes: 50,
        level: "لمختلف المستويات",
      },
      {
        id: "s2",
        day: "sat",
        type: "conditioning",
        time: "18:30",
        title: "تدريب الدوائر",
        minutes: 45,
        level: "بإيقاعك الخاص",
      },
      {
        id: "s3",
        day: "sun",
        type: "mobility",
        time: "08:00",
        title: "حركة ومرونة",
        minutes: 40,
        level: "لمختلف المستويات",
      },
      {
        id: "s4",
        day: "sun",
        type: "strength",
        time: "19:00",
        title: "نتدرّب معاً",
        minutes: 50,
        level: "لمختلف المستويات",
      },
      {
        id: "s5",
        day: "mon",
        type: "conditioning",
        time: "18:00",
        title: "إيقاع اللياقة",
        minutes: 45,
        level: "بإيقاعك الخاص",
      },
      {
        id: "s6",
        day: "tue",
        type: "strength",
        time: "07:00",
        title: "أساسيات القوة",
        minutes: 50,
        level: "لمختلف المستويات",
      },
      {
        id: "s7",
        day: "wed",
        type: "mobility",
        time: "18:30",
        title: "حركة ومرونة",
        minutes: 40,
        level: "لمختلف المستويات",
      },
      {
        id: "s8",
        day: "thu",
        type: "conditioning",
        time: "17:00",
        title: "تدريب الدوائر",
        minutes: 45,
        level: "بإيقاعك الخاص",
      },
    ],
  },
  plans: {
    eyebrow: "٠٣ / أسبوعك وعضويتك",
    title: "اختر إيقاعك.",
    text: "ثلاث عضويات نموذجية بأسعار شهرية توضيحية بالدينار العراقي. هذه الصفحة لا تنشئ اشتراكاً ولا تستلم أي دفعة.",
    currency: "د.ع",
    period: "/ شهر",
    choose: "اختر هذه العضوية",
    selected: "العضوية المختارة",
    popular: "الخيار المتوازن",
    items: [
      {
        id: "base",
        name: "أساسي",
        price: "٧٥٬٠٠٠",
        text: "لروتين تدريبك الخاص.",
        features: [
          "التدريب في المساحات المفتوحة",
          "مساحتا القوة والمرونة",
          "تعريف بالمكان في الزيارة الأولى",
        ],
      },
      {
        id: "flow",
        name: "حركة",
        price: "١١٠٬٠٠٠",
        text: "روتينك مع إيقاع المجموعة.",
        features: [
          "كل مزايا العضوية الأساسية",
          "أربع حصص جماعية شهرياً",
          "الوصول إلى جدول الحصص",
        ],
      },
      {
        id: "all",
        name: "شامل",
        price: "١٥٥٬٠٠٠",
        text: "مساحة أكبر لأسبوع متنوع.",
        features: [
          "كل مزايا عضوية حركة",
          "حصص جماعية نموذجية غير محدودة",
          "جلسة نقاش مع المدرب كل شهر",
        ],
      },
    ],
  },
  coaches: {
    eyebrow: "٠٤ / الإنسان قبل الأرقام",
    title: "مساحة للتوجيه.\nبلا استعراض.",
    text: "اسأل، وناقش طريقة الحركة، واختر نهجاً يناسب تجربتك. هذه البطاقات الرمزية توضح طريقة تقديم فريق التدريب دون صور لأشخاص غير حقيقيين.",
    badge: "أدوار تدريبية توضيحية",
    items: [
      {
        initials: "ق",
        title: "تدريب القوة",
        role: "التقنية · تخطيط الحصة",
        text: "حوار عن تجربتك في التدريب وما تريد التركيز عليه في الحصة القادمة.",
      },
      {
        initials: "ح",
        title: "تدريب الحركة",
        role: "المرونة · الحصص الجماعية",
        text: "مساحة لطرح الأسئلة واستكشاف الحركة والتدرّب بإيقاع يناسبك.",
      },
    ],
  },
  faq: {
    eyebrow: "قبل أن تبدأ",
    title: "أسئلة في محلها.",
    items: [
      {
        q: "هل أحتاج خبرة سابقة بالتدريب؟",
        a: "هذا التصور يرحب بمستويات مختلفة. عند زيارة نادٍ فعلي، تحدث مع الفريق عن تجربتك والتعريف المناسب لك قبل الانضمام إلى الحصة.",
      },
      {
        q: "هل أستطيع استكشاف حصة قبل اختيار العضوية؟",
        a: "نعم. اختر حصة نموذجية من الجدول وافتح نموذج التجربة. إرسال النموذج هنا يعرض تأكيداً محلياً فقط.",
      },
      {
        q: "هل الأسعار والعضويات حقيقية؟",
        a: "لا. الخطط والأسعار والجدول محتوى توضيحي. النموذج لا يرسل بيانات ولا يستلم دفعات ولا ينشئ عضوية.",
      },
      {
        q: "ماذا أحضر في زيارتي الأولى؟",
        a: "ملابس مريحة للتدريب وحذاء مناسب وقنينة ماء، وأي أسئلة تريد طرحها على الفريق. تأكد من مرافق النادي ومتطلباته عند ترتيب زيارة فعلية.",
      },
    ],
  },
  contact: {
    eyebrow: "خطوتك القادمة",
    title: "البداية\nأن تحضر.",
    text: "استكشف تجربة الزيارة الأولى بهذا النموذج التوضيحي. لن تُرسل أي بيانات شخصية.",
    button: "افتح نموذج التجربة",
    location: "بغداد · موقع افتراضي",
    hoursLabel: "ساعات عمل توضيحية",
    hours: "السبت–الخميس / ٠٦:٠٠–٢٣:٠٠",
    note: "نبض نادٍ رياضي خيالي. هذا نموذج تفاعلي لموقع، وليس خدمة حجز في نادٍ فعلي.",
    back: "إلى أعلى الصفحة",
  },
  form: {
    title: "خطط لزيارتك الأولى.",
    intro:
      "اختر عضوية نموذجية وجرّب النموذج. لن يُنشأ حجز أو اشتراك ولن تُحصّل أي دفعة.",
    close: "إغلاق التسجيل",
    plan: "العضوية النموذجية",
    session: "الحصة النموذجية المختارة",
    name: "الاسم",
    namePh: "استخدم اسماً تجريبياً",
    email: "البريد الإلكتروني",
    emailPh: "name@example.com",
    phone: "الهاتف (اختياري)",
    phonePh: "رقم هاتف تجريبي",
    preference: "ماذا تريد أن تستكشف؟",
    preferencePh: "اختر مجال التدريب",
    submit: "جرّب التسجيل",
    note: "للتجربة فقط. لا إرسال للبيانات ولا دفع.",
    success: {
      title: "اكتملت تجربة النموذج.",
      text: "لم تُرسل بياناتك، ولم يُحجز موعد، ولم تُحصّل أي دفعة.",
      again: "جرّب النموذج مرة أخرى",
    },
  },
};
export const gymContent: Record<DemoLang, GymContent> = { en, ar };
