import type { DemoLang } from "@/demos/config";

const en = {
  name: "Sara Kamel",
  first: "Sara",
  last: "Kamel",
  role: "Photographer",
  nav: { work: "Work", about: "About", services: "Services", contact: "Contact" },
  cta: "Book a session",
  hero: {
    eyebrow: "Portrait · Wedding · Editorial — Baghdad",
    statement: "I photograph people the way they hope to be remembered: honest, unhurried, and in beautiful light.",
    scroll: "Scroll to view the work",
    heroAlt: "Mountains at dusk in warm duotone light",
  },
  marquee: ["Portraits", "Weddings", "Landscapes", "Urban", "Editorial", "Commercial"],
  work: {
    eyebrow: "Selected work",
    title: "The work",
    text: "A rolling selection from the last two years. Every image is delivered fully edited, in print and web resolution.",
    categories: [
      { key: "portrait", label: "Portrait" },
      { key: "wedding", label: "Wedding" },
      { key: "landscape", label: "Landscape" },
      { key: "urban", label: "Urban" },
    ],
    alts: {
      "photo-01": "Studio portrait against soft grey light",
      "photo-02": "Layered mountains at sunset",
      "photo-03": "City skyline at night with lit windows",
      "photo-04": "Bride and groom in rose-toned light",
      "photo-05": "Sea horizon with the sun reflecting on water",
      "photo-06": "Portrait in warm sand tones",
      "photo-07": "Desert dunes under a pale sun",
      "photo-08": "Monochrome skyline",
      "photo-09": "Couple at dusk during a wedding",
      "photo-10": "Night mountains under a golden moon",
      "photo-11": "Portrait in rose light",
      "photo-12": "Monochrome seascape with a red sun",
    },
  },
  about: {
    eyebrow: "About",
    title: "Eight years, two cameras, one rule: no forced smiles.",
    text: "I started photographing my sister's wedding with a borrowed camera in 2017 and never gave it back. Since then I have shot more than two hundred sessions across Iraq, from studio portraits in Baghdad to weddings in Erbil and brand campaigns in Basra. My work has appeared in local magazines and on the walls of people who trust me with their most important days.",
    facts: [
      { value: "+200", label: "Sessions" },
      { value: "8", label: "Years" },
      { value: "40", label: "Weddings" },
      { value: "3", label: "Exhibitions" },
    ],
    gear: "Shot on Sony A7 IV and Fujifilm X-T5 · Natural light wherever possible",
  },
  services: {
    eyebrow: "Services",
    title: "Simple packages, clear prices",
    text: "Every package includes a planning call, professional editing and an online gallery for sharing and downloads.",
    currency: "IQD",
    items: [
      {
        name: "Portrait session",
        price: "250,000",
        duration: "90 minutes",
        features: ["One location", "25 edited images", "Online gallery", "Delivery in 7 days"],
      },
      {
        name: "Wedding day",
        price: "1,500,000",
        duration: "Up to 10 hours",
        features: [
          "Two photographers",
          "400+ edited images",
          "Printed album 30×30",
          "Highlights within 48 hours",
        ],
        featured: true,
      },
      {
        name: "Brand & editorial",
        price: "600,000",
        duration: "Half day",
        features: ["Creative direction", "60 edited images", "Commercial licence", "Studio or on location"],
      },
    ],
    from: "from",
    choose: "Choose this package",
  },
  process: {
    title: "How a session works",
    steps: [
      { title: "Plan", text: "A short call about the mood, location and wardrobe." },
      { title: "Shoot", text: "Relaxed direction, real moments, beautiful light." },
      { title: "Deliver", text: "A private gallery with edited images and print options." },
    ],
  },
  testimonials: [
    {
      quote: "She made us forget the camera was there. The photos look like how the day felt.",
      name: "Noor & Ahmed",
      role: "Wedding, Erbil",
    },
    {
      quote: "Professional, punctual and creative — our campaign images doubled engagement.",
      name: "Dijla Coffee",
      role: "Brand campaign",
    },
  ],
  contact: {
    eyebrow: "Booking",
    title: "Let's make something worth keeping.",
    text: "Tell me about the session you have in mind. I answer every message within 24 hours.",
    fields: {
      name: "Name",
      email: "Email",
      phone: "Phone / WhatsApp",
      type: "Session type",
      typePh: "Choose a session",
      date: "Preferred date",
      message: "Tell me about it",
      messagePh: "Location ideas, number of people, the mood you're after…",
    },
    submit: "Send booking request",
    success: {
      title: "Got it!",
      text: "Thank you — I'll reply within 24 hours to confirm details.",
      again: "Send another request",
    },
    note: "Demo form — nothing is actually sent.",
    email: "hello@sarakamel.example",
    phone: "+964 771 000 0000",
    based: "Based in Baghdad · Available across Iraq",
  },
  footer: {
    rights: "All rights reserved.",
    social: ["Instagram", "Behance", "Pinterest"],
  },
};

export type PhotographerContent = typeof en;

const ar: PhotographerContent = {
  name: "سارة كامل",
  first: "سارة",
  last: "كامل",
  role: "مصوّرة",
  nav: { work: "الأعمال", about: "عني", services: "الباقات", contact: "تواصل" },
  cta: "احجز جلسة",
  hero: {
    eyebrow: "بورتريه · أعراس · تحريري — بغداد",
    statement: "أصوّر الناس كما يتمنون أن يُذكروا: بصدق، دون عجلة، وفي ضوءٍ جميل.",
    scroll: "مرّر لاستعراض الأعمال",
    heroAlt: "جبال عند الغسق بضوء دافئ ثنائي اللون",
  },
  marquee: ["بورتريه", "أعراس", "طبيعة", "مدينة", "تحريري", "تجاري"],
  work: {
    eyebrow: "أعمال مختارة",
    title: "الأعمال",
    text: "مختارات متجددة من العامين الأخيرين. تُسلَّم كل صورة معدّلة بالكامل، بدقة الطباعة والويب.",
    categories: [
      { key: "portrait", label: "بورتريه" },
      { key: "wedding", label: "أعراس" },
      { key: "landscape", label: "طبيعة" },
      { key: "urban", label: "مدينة" },
    ],
    alts: {
      "photo-01": "بورتريه استوديو بإضاءة رمادية ناعمة",
      "photo-02": "جبال متدرجة عند الغروب",
      "photo-03": "أفق المدينة ليلاً بنوافذ مضاءة",
      "photo-04": "عروسان في ضوء وردي",
      "photo-05": "أفق البحر وانعكاس الشمس على الماء",
      "photo-06": "بورتريه بدرجات رملية دافئة",
      "photo-07": "كثبان صحراوية تحت شمس شاحبة",
      "photo-08": "أفق مدينة بالأبيض والأسود",
      "photo-09": "عروسان عند الغسق",
      "photo-10": "جبال ليلية تحت قمر ذهبي",
      "photo-11": "بورتريه في ضوء وردي",
      "photo-12": "منظر بحري أحادي اللون بشمس حمراء",
    },
  },
  about: {
    eyebrow: "عني",
    title: "ثماني سنوات، كاميرتان، وقاعدة واحدة: لا ابتسامات مصطنعة.",
    text: "بدأتُ بتصوير زفاف أختي بكاميرا مستعارة عام 2017 ولم أُعِدها أبداً. منذ ذلك الحين صوّرتُ أكثر من مئتي جلسة في عموم العراق، من بورتريهات الاستوديو في بغداد إلى الأعراس في أربيل وحملات العلامات التجارية في البصرة. نُشرت أعمالي في مجلات محلية وعلى جدران أشخاص ائتمنوني على أهم أيامهم.",
    facts: [
      { value: "+200", label: "جلسة" },
      { value: "8", label: "سنوات" },
      { value: "40", label: "زفافاً" },
      { value: "3", label: "معارض" },
    ],
    gear: "تصوير بكاميرا Sony A7 IV وFujifilm X-T5 · ضوء طبيعي كلما أمكن",
  },
  services: {
    eyebrow: "الباقات",
    title: "باقات بسيطة وأسعار واضحة",
    text: "تشمل كل باقة مكالمة تخطيط، تعديلاً احترافياً، ومعرضاً إلكترونياً للمشاركة والتحميل.",
    currency: "د.ع",
    items: [
      {
        name: "جلسة بورتريه",
        price: "250,000",
        duration: "90 دقيقة",
        features: ["موقع واحد", "25 صورة معدّلة", "معرض إلكتروني", "التسليم خلال 7 أيام"],
      },
      {
        name: "يوم الزفاف",
        price: "1,500,000",
        duration: "حتى 10 ساعات",
        features: ["مصوّران", "+400 صورة معدّلة", "ألبوم مطبوع 30×30", "أبرز اللقطات خلال 48 ساعة"],
        featured: true,
      },
      {
        name: "علامات تجارية وتحريري",
        price: "600,000",
        duration: "نصف يوم",
        features: ["إخراج إبداعي", "60 صورة معدّلة", "رخصة استخدام تجاري", "استوديو أو موقع خارجي"],
      },
    ],
    from: "ابتداءً من",
    choose: "اختر هذه الباقة",
  },
  process: {
    title: "كيف تسير الجلسة",
    steps: [
      { title: "التخطيط", text: "مكالمة قصيرة عن الأجواء والموقع والملابس." },
      { title: "التصوير", text: "توجيه مريح، لحظات حقيقية، وضوء جميل." },
      { title: "التسليم", text: "معرض خاص بالصور المعدّلة وخيارات الطباعة." },
    ],
  },
  testimonials: [
    {
      quote: "جعلتنا ننسى وجود الكاميرا. الصور تبدو تماماً كما شعرنا بذلك اليوم.",
      name: "نور وأحمد",
      role: "زفاف، أربيل",
    },
    {
      quote: "احترافية ودقيقة في المواعيد ومبدعة — صور حملتنا ضاعفت التفاعل.",
      name: "قهوة دجلة",
      role: "حملة علامة تجارية",
    },
  ],
  contact: {
    eyebrow: "الحجز",
    title: "لنصنع شيئاً يستحق الاحتفاظ به.",
    text: "أخبريني/أخبرني عن الجلسة التي تفكر بها. أردّ على كل رسالة خلال 24 ساعة.",
    fields: {
      name: "الاسم",
      email: "البريد الإلكتروني",
      phone: "الهاتف / واتساب",
      type: "نوع الجلسة",
      typePh: "اختر الجلسة",
      date: "التاريخ المفضل",
      message: "حدّثني عنها",
      messagePh: "أفكار عن الموقع، عدد الأشخاص، الأجواء التي تريدها…",
    },
    submit: "إرسال طلب الحجز",
    success: {
      title: "وصلني طلبك!",
      text: "شكراً لك — سأرد خلال 24 ساعة لتأكيد التفاصيل.",
      again: "إرسال طلب آخر",
    },
    note: "نموذج تجريبي — لا يتم إرسال أي بيانات.",
    email: "hello@sarakamel.example",
    phone: "+964 771 000 0000",
    based: "مقيمة في بغداد · متاحة في عموم العراق",
  },
  footer: {
    rights: "جميع الحقوق محفوظة.",
    social: ["Instagram", "Behance", "Pinterest"],
  },
};

export const photographerContent: Record<DemoLang, PhotographerContent> = { ar, en };

export const PHOTOS: { id: keyof typeof en.work.alts; category: string; ratio: number }[] = [
  { id: "photo-01", category: "portrait", ratio: 0.8 },
  { id: "photo-02", category: "landscape", ratio: 1.6 },
  { id: "photo-03", category: "urban", ratio: 1 },
  { id: "photo-04", category: "wedding", ratio: 0.8 },
  { id: "photo-05", category: "landscape", ratio: 1.6 },
  { id: "photo-06", category: "portrait", ratio: 0.8 },
  { id: "photo-07", category: "landscape", ratio: 1.6 },
  { id: "photo-08", category: "urban", ratio: 1 },
  { id: "photo-09", category: "wedding", ratio: 0.8 },
  { id: "photo-10", category: "landscape", ratio: 1.6 },
  { id: "photo-11", category: "portrait", ratio: 1 },
  { id: "photo-12", category: "landscape", ratio: 1.6 },
];
