import type { DemoLang } from "@/demos/config";

const en = {
  brand: "Elite Dental",
  brandSub: "Clinic · Baghdad",
  nav: { services: "Services", doctors: "Doctors", about: "Why us", faq: "FAQ", contact: "Contact" },
  cta: "Book an appointment",
  hero: {
    eyebrow: "Al-Mansour · Open 6 days a week",
    title: "Healthy smiles,",
    titleAccent: "gentle care.",
    text: "Modern dentistry for the whole family — from routine check-ups to implants and orthodontics — with digital X-rays, painless anaesthesia and transparent prices.",
    primary: "Book now",
    secondary: "View services",
    badges: ["Same-day emergency", "Digital X-ray & 3D scan", "Insurance accepted"],
    quick: {
      title: "Quick appointment",
      name: "Your name",
      phone: "Phone",
      service: "Service",
      servicePh: "Choose",
      submit: "Request appointment",
      success: { title: "Request sent", text: "Reception will call you within an hour during working time.", again: "Book another" },
      note: "Demo — nothing is sent.",
    },
  },
  stats: [
    { value: "+12,000", label: "Happy patients" },
    { value: "14", label: "Years of care" },
    { value: "6", label: "Specialists" },
    { value: "4.9", label: "Google rating" },
  ],
  services: {
    eyebrow: "Services",
    title: "Everything your smile needs, under one roof",
    text: "Prices are starting points per session; you receive a written plan before any treatment begins.",
    from: "from",
    currency: "IQD",
    items: [
      { icon: "check", title: "Check-up & cleaning", text: "Examination, digital X-ray and professional scaling.", price: "25,000" },
      { icon: "sparkles", title: "Teeth whitening", text: "In-clinic laser whitening in one 60-minute visit.", price: "150,000" },
      { icon: "braces", title: "Orthodontics", text: "Metal, ceramic and clear aligners for teens and adults.", price: "900,000" },
      { icon: "implant", title: "Dental implants", text: "Swiss implants with 3D-guided placement and a 10-year guarantee.", price: "650,000" },
      { icon: "child", title: "Paediatric dentistry", text: "Gentle care, fluoride and sealants in a child-friendly room.", price: "20,000" },
      { icon: "root", title: "Root canal", text: "Microscope-assisted endodontics, usually in a single visit.", price: "120,000" },
      { icon: "veneer", title: "Veneers & crowns", text: "E-max and zirconia restorations designed digitally.", price: "250,000" },
      { icon: "emergency", title: "Emergency care", text: "Same-day appointments for pain, trauma and broken teeth.", price: "30,000" },
    ],
  },
  doctors: {
    eyebrow: "Our team",
    title: "Specialists you can trust",
    items: [
      { name: "Dr. Zahraa Al-Khafaji", role: "Orthodontist · Clinic director", bio: "BDS Baghdad, MSc Orthodontics (Cairo). 14 years in practice.", photo: "/demos/art/portrait-doctor-1.svg" },
      { name: "Dr. Yousif Al-Ani", role: "Implantologist & oral surgeon", bio: "Fellow of the ICOI. Over 2,000 implants placed.", photo: "/demos/art/portrait-doctor-2.svg" },
      { name: "Dr. Rania Salman", role: "Paediatric dentist", bio: "Specialist in children's dentistry and anxiety-free care.", photo: "/demos/art/portrait-doctor-3.svg" },
    ],
  },
  about: {
    eyebrow: "Why Elite Dental",
    title: "Technology that makes visits shorter and calmer",
    points: [
      { title: "Digital first", text: "Intra-oral scanners replace impressions; 3D CBCT scans plan every implant." },
      { title: "Painless approach", text: "Computer-controlled anaesthesia and sedation options for anxious patients." },
      { title: "Sterilisation you can see", text: "Sealed instrument packs opened in front of you, class-B autoclaves." },
      { title: "Clear pricing", text: "A written treatment plan with fixed prices before we start — no surprises." },
    ],
  },
  insurance: { title: "We work with", items: ["Al-Rafidain Insurance", "Iraq Insurance Co.", "Al-Ameen Takaful", "Qi Card health", "Asiacell Care"] },
  testimonials: {
    eyebrow: "Patient stories",
    title: "What our patients say",
    items: [
      { quote: "I was terrified of dentists. Dr. Zahraa's team explained every step and I felt nothing. Braces off in 14 months!", name: "Hiba M.", role: "Orthodontics" },
      { quote: "Implant placed and crowned within three months, exactly as planned and priced.", name: "Karrar S.", role: "Implant" },
      { quote: "My kids actually ask to go back. The paediatric room is wonderful.", name: "Umm Yousif", role: "Paediatric care" },
    ],
  },
  faq: {
    eyebrow: "FAQ",
    title: "Good to know before your visit",
    items: [
      { q: "Do I need an appointment?", a: "Walk-ins are welcome for emergencies. For everything else, booking online or by phone guarantees your slot and shortens the visit." },
      { q: "Is the first consultation free?", a: "Yes. The consultation and treatment plan are free; you only pay for X-rays if they are needed (10,000 IQD)." },
      { q: "Do you accept insurance?", a: "We accept the insurers listed above and issue detailed invoices for any other reimbursement." },
      { q: "Can treatment be paid in instalments?", a: "Orthodontics and implants can be split into monthly payments at no extra cost." },
      { q: "Where do I park?", a: "Free patient parking is available behind the building on 14 Ramadan Street." },
    ],
  },
  contact: {
    eyebrow: "Book",
    title: "Book your appointment",
    text: "Choose a service and a preferred time. Reception confirms by phone or WhatsApp.",
    fields: {
      name: "Full name",
      phone: "Phone / WhatsApp",
      service: "Service",
      servicePh: "Choose a service",
      doctor: "Preferred doctor",
      doctorPh: "Any available",
      date: "Preferred date",
      time: "Preferred time",
      notes: "Notes",
      notesPh: "Pain, previous treatment, questions…",
    },
    submit: "Request appointment",
    success: { title: "Appointment requested", text: "Thank you — reception will confirm your slot shortly.", again: "Book another appointment" },
    note: "Demo form — nothing is actually sent.",
    hours: {
      title: "Opening hours",
      rows: [
        { days: "Saturday – Thursday", time: "9:00 – 21:00" },
        { days: "Friday", time: "Closed (emergency line only)" },
      ],
    },
    address: "14 Ramadan Street, Al-Mansour, Baghdad — 2nd floor",
    phone: "+964 780 100 0000",
    emergency: "Emergency line",
    labels: { address: "Address", phone: "Reception" },
  },
  footer: { tagline: "Family dentistry in Al-Mansour since 2012.", rights: "All rights reserved." },
};

export type ClinicContent = typeof en;

const ar: ClinicContent = {
  brand: "عيادة النخبة",
  brandSub: "لطب الأسنان · بغداد",
  nav: { services: "الخدمات", doctors: "الأطباء", about: "لماذا نحن", faq: "أسئلة شائعة", contact: "تواصل" },
  cta: "احجز موعداً",
  hero: {
    eyebrow: "المنصور · مفتوح 6 أيام في الأسبوع",
    title: "ابتسامة صحية،",
    titleAccent: "بعناية لطيفة.",
    text: "طب أسنان حديث لكل العائلة — من الفحص الدوري إلى الزراعة والتقويم — بأشعة رقمية وتخدير بلا ألم وأسعار واضحة.",
    primary: "احجز الآن",
    secondary: "استعرض الخدمات",
    badges: ["طوارئ في اليوم نفسه", "أشعة رقمية ومسح ثلاثي الأبعاد", "نقبل التأمين"],
    quick: {
      title: "موعد سريع",
      name: "اسمك",
      phone: "الهاتف",
      service: "الخدمة",
      servicePh: "اختر",
      submit: "طلب موعد",
      success: { title: "تم إرسال الطلب", text: "سيتصل بك الاستقبال خلال ساعة في أوقات الدوام.", again: "حجز آخر" },
      note: "تجريبي — لا يُرسل شيء.",
    },
  },
  stats: [
    { value: "+12,000", label: "مريض سعيد" },
    { value: "14", label: "عاماً من الرعاية" },
    { value: "6", label: "اختصاصيين" },
    { value: "4.9", label: "تقييم Google" },
  ],
  services: {
    eyebrow: "الخدمات",
    title: "كل ما تحتاجه ابتسامتك في مكان واحد",
    text: "الأسعار نقطة بداية لكل جلسة؛ تستلم خطة علاج مكتوبة قبل بدء أي إجراء.",
    from: "ابتداءً من",
    currency: "د.ع",
    items: [
      { icon: "check", title: "فحص وتنظيف", text: "فحص وأشعة رقمية وتنظيف احترافي للجير.", price: "25,000" },
      { icon: "sparkles", title: "تبييض الأسنان", text: "تبييض بالليزر داخل العيادة في زيارة واحدة مدتها 60 دقيقة.", price: "150,000" },
      { icon: "braces", title: "تقويم الأسنان", text: "تقويم معدني وخزفي وشفاف للمراهقين والبالغين.", price: "900,000" },
      { icon: "implant", title: "زراعة الأسنان", text: "زرعات سويسرية بتوجيه ثلاثي الأبعاد وضمان 10 سنوات.", price: "650,000" },
      { icon: "child", title: "طب أسنان الأطفال", text: "عناية لطيفة وفلورايد وحشوات وقائية في غرفة مخصصة للأطفال.", price: "20,000" },
      { icon: "root", title: "علاج العصب", text: "علاج جذور بمساعدة المجهر، غالباً في زيارة واحدة.", price: "120,000" },
      { icon: "veneer", title: "الفينير والتيجان", text: "ترميمات E-max وزيركون مصممة رقمياً.", price: "250,000" },
      { icon: "emergency", title: "حالات الطوارئ", text: "مواعيد في اليوم نفسه للألم والإصابات والكسور.", price: "30,000" },
    ],
  },
  doctors: {
    eyebrow: "فريقنا",
    title: "اختصاصيون تثق بهم",
    items: [
      { name: "د. زهراء الخفاجي", role: "اختصاصية تقويم · مديرة العيادة", bio: "بكالوريوس طب أسنان بغداد، ماجستير تقويم (القاهرة). 14 عاماً من الممارسة.", photo: "/demos/art/portrait-doctor-1.svg" },
      { name: "د. يوسف العاني", role: "اختصاصي زراعة وجراحة فم", bio: "زميل ICOI. أكثر من 2,000 زرعة.", photo: "/demos/art/portrait-doctor-2.svg" },
      { name: "د. رانيا سلمان", role: "اختصاصية أسنان أطفال", bio: "متخصصة في طب أسنان الأطفال والعلاج دون قلق.", photo: "/demos/art/portrait-doctor-3.svg" },
    ],
  },
  about: {
    eyebrow: "لماذا عيادة النخبة",
    title: "تقنية تجعل الزيارة أقصر وأهدأ",
    points: [
      { title: "رقمي أولاً", text: "ماسحات داخل الفم بدل الطبعات؛ ومسح CBCT ثلاثي الأبعاد لتخطيط كل زرعة." },
      { title: "نهج بلا ألم", text: "تخدير بالتحكم الحاسوبي وخيارات تهدئة للمرضى القلقين." },
      { title: "تعقيم تراه بعينك", text: "أدوات معقمة مغلفة تُفتح أمامك، وأجهزة تعقيم من الفئة B." },
      { title: "أسعار واضحة", text: "خطة علاج مكتوبة بأسعار ثابتة قبل أن نبدأ — بلا مفاجآت." },
    ],
  },
  insurance: { title: "نتعامل مع", items: ["الرافدين للتأمين", "شركة التأمين العراقية", "الأمين تكافل", "كي كارد الصحية", "آسياسيل كير"] },
  testimonials: {
    eyebrow: "قصص المرضى",
    title: "ماذا يقول مرضانا",
    items: [
      { quote: "كنت أخاف من طبيب الأسنان. فريق د. زهراء شرح كل خطوة ولم أشعر بشيء. أزلت التقويم خلال 14 شهراً!", name: "هبة م.", role: "تقويم" },
      { quote: "زراعة وتركيب التاج خلال ثلاثة أشهر، تماماً كما خُطط وسُعّر.", name: "كرار س.", role: "زراعة" },
      { quote: "أطفالي يطلبون العودة فعلاً. غرفة الأطفال رائعة.", name: "أم يوسف", role: "أسنان أطفال" },
    ],
  },
  faq: {
    eyebrow: "أسئلة شائعة",
    title: "يهمك معرفته قبل زيارتك",
    items: [
      { q: "هل أحتاج إلى موعد؟", a: "نستقبل الطوارئ دون موعد. لبقية الحالات، الحجز عبر الموقع أو الهاتف يضمن وقتك ويختصر الزيارة." },
      { q: "هل الاستشارة الأولى مجانية؟", a: "نعم. الاستشارة وخطة العلاج مجانيتان؛ تدفع فقط ثمن الأشعة إن لزمت (10,000 دينار)." },
      { q: "هل تقبلون التأمين؟", a: "نقبل شركات التأمين المذكورة أعلاه ونصدر فواتير مفصلة لأي جهة أخرى." },
      { q: "هل يمكن تقسيط العلاج؟", a: "يمكن تقسيط التقويم والزراعة على دفعات شهرية دون أي كلفة إضافية." },
      { q: "أين أركن السيارة؟", a: "موقف مجاني للمرضى خلف البناية على شارع 14 رمضان." },
    ],
  },
  contact: {
    eyebrow: "الحجز",
    title: "احجز موعدك",
    text: "اختر الخدمة والوقت المناسب، ويؤكد الاستقبال عبر الهاتف أو واتساب.",
    fields: {
      name: "الاسم الكامل",
      phone: "الهاتف / واتساب",
      service: "الخدمة",
      servicePh: "اختر الخدمة",
      doctor: "الطبيب المفضل",
      doctorPh: "أي طبيب متاح",
      date: "التاريخ المفضل",
      time: "الوقت المفضل",
      notes: "ملاحظات",
      notesPh: "ألم، علاج سابق، أسئلة…",
    },
    submit: "طلب موعد",
    success: { title: "تم طلب الموعد", text: "شكراً لك — سيؤكد الاستقبال موعدك قريباً.", again: "حجز موعد آخر" },
    note: "نموذج تجريبي — لا يتم إرسال أي بيانات.",
    hours: {
      title: "ساعات العمل",
      rows: [
        { days: "السبت – الخميس", time: "9:00 – 21:00" },
        { days: "الجمعة", time: "مغلق (خط الطوارئ فقط)" },
      ],
    },
    address: "شارع 14 رمضان، المنصور، بغداد — الطابق الثاني",
    phone: "+964 780 100 0000",
    emergency: "خط الطوارئ",
    labels: { address: "العنوان", phone: "الاستقبال" },
  },
  footer: { tagline: "طب أسنان للعائلة في المنصور منذ 2012.", rights: "جميع الحقوق محفوظة." },
};

export const clinicContent: Record<DemoLang, ClinicContent> = { ar, en };
